-- lefta.app — an invoice can only be created with the columns a person fills in
--
-- `20260815120100_rls.sql` revoked UPDATE on `invoices` and handed it back one
-- column at a time, so a browser session cannot rewrite a settlement. The
-- comment there spells out why: the settlement columns "are written by the
-- Stripe webhook under the service role".
--
-- INSERT was never revoked. Supabase hands `authenticated` a table-wide INSERT
-- by default, and `invoices_insert_active` constrains only `user_id` and the
-- write role — so a member could post a row straight to PostgREST carrying
-- `status = 'paid'`, `paid_at`, `paid_amount_cents` and a
-- `stripe_payment_intent_id` that never existed, inventing a card payment in
-- their own company's books. Not a cross-tenant hole: `user_id` is pinned by the
-- policy and `debtor_id` by the composite foreign key. But it defeats exactly
-- what restricting UPDATE was for, and it makes the "collected through lefta"
-- figure forgeable from the browser.
--
-- Same shape as the UPDATE grant: revoke at table level first, because a
-- column-level REVOKE against a table-wide grant is silently a no-op.
--
-- The list is what `createInvoice` actually writes. Deliberately absent:
-- `status` (defaults to pending — an invoice is not created settled), every
-- settlement and provider-reference column, and `pay_token` / `short_code`,
-- which are generated by column defaults so no privilege is needed to omit
-- them. That last one is the point of `20260815203000_short_pay_code.sql`: a
-- session must not be able to choose a payment credential.

revoke insert on public.invoices from anon, authenticated;

grant insert (
  user_id, debtor_id, invoice_number, series, amount_cents, currency,
  issue_date, due_date, mark, source, automation_enabled, scenario_mode
) on public.invoices to authenticated;
